services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.app
      target: final
    container_name: taftacrm
    ports:
      - 8080:8080
    depends_on:
      - db
      - adminer
    restart: always
  
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    container_name: postgresql_db
    ports:
      - 5432:5432
    volumes:
      - taftacrm_data:/var/lib/postgresql/data
    restart: always

  adminer:
    image: adminer:4.8.1-standalone
    container_name: adminer
    ports:
      - 8082:8080
    depends_on:
      - db
    restart: always

volumes:
  taftacrm_data: