using TaftaCRM.Helpers;

namespace TaftaCRM.Models.Internal.System.Static;

public enum UserAccountRole
{
    // super user (not available, generated by system only)
    [StringValue("Super User")]
    sudo,

    [StringValue("Administrator")]
    Administrator,

    [StringValue("User")]
    User,

    [StringValue("Guest")]
    Guest
}